/* ide-layout-manager.c
 *
 * Copyright (C) 2015 Christian Hergert <chergert@redhat.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "ide-layout-manager.h"

G_DEFINE_INTERFACE (IdeLayoutManager, ide_layout_manager, G_TYPE_OBJECT)

static void
ide_layout_manager_default_init (IdeLayoutManagerInterface *iface)
{
}

/**
 * ide_layout_manager_add:
 * @self: An #IdeLayoutManager.
 * @hints: (nullable): optional hints for the layout.
 * @child: A #GtkWidget.
 *
 * Adds @child to the layout, optionally hinting to the layout manager about where to
 * place the child.
 *
 * Returns: A layout specific identifier greater than zero, which should be passed to
 *   ide_layout_manager_remove() to remove the widget from the layout.
 */
guint
ide_layout_manager_add (IdeLayoutManager     *self,
                        const IdeLayoutHints *hints,
                        GtkWidget            *child)
{
  guint ret;

  g_return_val_if_fail (IDE_IS_LAYOUT_MANAGER (self), 0);
  g_return_val_if_fail (GTK_IS_WIDGET (child), 0);

  ret = IDE_LAYOUT_MANAGER_GET_IFACE (self)->add (self, hints, child);

  g_return_val_if_fail (ret > 0, 0);

  return ret;
}

/**
 * ide_layout_manager_remove:
 * @self: An #IdeLayoutManager.
 * @layout_id: The layout id from ide_layout_manager_add()
 *
 * Removes a widget from the layout that was generated by calling * ide_layout_manager_add().
 */
void
ide_layout_manager_remove (IdeLayoutManager *self,
                           guint             layout_id)
{
  g_return_if_fail (IDE_IS_LAYOUT_MANAGER (self));
  g_return_if_fail (layout_id > 0);

  IDE_LAYOUT_MANAGER_GET_IFACE (self)->remove (self, layout_id);
}
