bin_PROGRAMS = {{name}}

{{if language == "c"}}
{{prefix_}}_SOURCES = main.c
{{prefix_}}_CFLAGS = $({{PREFIX}}_CFLAGS)
{{else if language == "c++"}}
{{prefix_}}_SOURCES = main.cpp
{{prefix_}}_CPPFLAGS = $({{PREFIX}}_CFLAGS)
{{else if language == "vala"}}
{{prefix_}}_SOURCES = main.vala
{{prefix_}}_CPPFLAGS = $({{PREFIX}}_CFLAGS)
{{prefix_}}_VALAFLAGS = --pkg gtk+-3.0
{{end}}

{{prefix_}}_LDADD = $({{PREFIX}}_LIBS)

-include $(top_srcdir)/git.mk
